version: '3'
services:
  mongodb:
    image: mongo:7.0
    container_name: mongoose-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      # - mongo-volumes:/data/db # 永続化しない
      - ./init:/docker-entrypoint-initdb.d:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    
  #volumes:
  #  mongo-volumes:
  #    name: mongodb-data