version: '3'
services:
  mongodb:
    image: mongo:7.0
    container_name: prisma-mongodb
    command: ["--replSet", "rs0", "--bind_ip_all", "--noauth"]
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./mongod.conf:/etc/mongod.conf